{{- if and .Values.persistence.data.enabled (not .Values.persistence.data.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ollama.fullname" . }}-data
  labels:
    {{- include "ollama.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
  {{- if .Values.persistence.data.storageClass }}
  storageClassName: {{ .Values.persistence.data.storageClass }}
  {{- end }}
{{- end }}
---
{{- if and .Values.persistence.models.enabled (not .Values.persistence.models.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ollama.fullname" . }}-models
  labels:
    {{- include "ollama.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.models.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.models.size }}
  {{- if .Values.persistence.models.storageClass }}
  storageClassName: {{ .Values.persistence.models.storageClass }}
  {{- end }}
{{- end }}